name: CI
on:
  pull_request:
  push:
    branches: [main, staging, trying]

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CI: 1
  RUST_BACKTRACE: short
  RUSTFLAGS: -D warnings
  RUSTUP_MAX_RETRIES: 10

jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, "windows-latest"]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
    - run: cargo test --all
    - run: cargo test --doc
    - run: cargo test --features std
    - run: make full-cycle
    - run: make integration
    - name: Test comparing against C signify
      if: matrix.os == 'ubuntu-latest'
      run: make compare

  check_fmt_and_docs:
    name: Checking fmt and docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy
        override: true

    - name: fmt
      run: cargo fmt --all -- --check

    - name: Clippy
      run: cargo clippy --all --all-targets --all-features

    - name: Docs
      run: cargo doc

  no_std_build:
    name: "Ensure no_std can build"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
    
    - name: Build
      run: |
        rustup target add thumbv6m-none-eabi
        cargo build -p libsignify --target thumbv6m-none-eabi
